### ISSUE TITLE
Service Now > dedicated format for time field

### ISSUE THREAD

**Issue by coppee** [ems-project/EMSFormBundle#61]
Hello David,
We need a dedicated format for all the time fields that we send to Service Now (1970-01-01 00:00:00). 

What is the best way ?
- Create a dedicated field in this bundle ?
- Create a dedicated Services/ServiceNowSubmissionRender with a Transformer in the Submission Bundle ?
- Other idea ?

Thanks !

**Comment by dameert** [comment]
Without looking at the code I would try to fit this in the model of a submission. A dedicated serviceNowDateTime object. That will always return the correct form when cast to a string. The model handles the transformation. Then the servicenow submission handler could instantiate this new model whenever a DateTime class is passed in the formdata. Does something like that seems possible?

**Comment by dameert** [comment]
So this would go in the submission bundle as we only care for this format after/on submit

**Comment by coppee** [comment]
Yep, sounds good. I look how to do something like that. 
Thanks.
